% Textures, developpement de Karhunen-Loeve.
%
%   MLaplace............Generation d'une matrice de Laplace.
%   GTexture............Generation de texture a 2 dimensions.
%   SpectreP............Evaluation du spectre de puissance.
%   BandePas............Evaluation de la bande-passante.
%   GNoyauM1............Generation d'un 'noyau' elementaire.
%   Im2Noyau............Generation d'un noyau a partir de l'image.
%   KLBase..............Diagonalisation d'un noyau.
%   KLM.................Decomposition de KL d'une image selon un noyau.
%   KLR.................Decomposition reelle de KL d'une d'une image.
%   Vect2Mat............Transforme un vecteur en matrice.
%   Compress............Compression d'une texture stationnaire.
%   Decompress..........Decompression d'une texture stationnaire.
%
%